version: '3.9'
services:
  mysql_db_container:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=qweqwe123
      - MYSQL_USER=pablo
      - MYSQL_PASSWORD=123pablo
    ports:
      - '3306:3306'
    volumes:
      - mysql_db_data_container:/var/lib/mysql
      - ./mysql_db_data_container/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer_container:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8081:8080
  
  mci-auth-service:
    image: mci-auth-service
    ports:
      - 3000:3000

volumes:
  mysql_db_data_container:
    driver: local