###
GET http://localhost:3000/users/

### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "userEmail": "john@doe.cl",
  "userPassword": "doeJhon"
}

### Auth sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "userEmail": "john@doe.cl",
  "userPassword": "doeJhon"
}

### Get the currently signed in user
GET http://localhost:3000/users/whoami

### Find a particular user with a given ID
GET http://localhost:3000/users/18
