###
GET http://localhost:3001/users/

### Create a new user
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
  "userEmail": "john@doe.cl",
  "userPassword": "doeJhon"
}

### Auth sign in
POST http://localhost:3001/auth/signin
Content-Type: application/json

{
  "userEmail": "john@doe.cl",
  "userPassword": "doeJhon"
}

### Sign out
Post http://localhost:3001/auth/signout

### Get the currently signed in user
GET http://localhost:3001/users/whoami

### Find a particular user with a given ID
GET http://localhost:3001/users/18


### Google

Get http://localhost:3001/auth/signin/google
