http:
  host: '127.0.0.1'
  port: 3001

db:
  mysql:
    URL: 'localhost'
    PORT: 3306
    DATABASE: 'users'
    USER: 'root'
    PASSWORD: 'qweqwe123'

sessions:
  multiSessionAllowed: true
  maxSessionsLimit: 2

cookieSession:
  secret: 'cookie-session-secret-777'

googleStrategy:
  secret: 'google-strategy-secret-777'
  saveUninitialized: false
  reSave: false
  cookie: 
    maxAge: 60000

oauth:
  clientId: '16504654868-dasc0feh72hfbna1g1c9gmcicc07e8ot.apps.googleusercontent.com'
  clientSecret: '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'
  callbackUrl: 'http://localhost:3001/api/auth/google/redirect'

mongo:
  uri: 'mongodb://mongodb_container:27017/sessions'